# Generated by Django 2.1.5 on 2020-07-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='resource_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.CharField(max_length=30),
        ),
    ]
